# vim: set ft=yaml ts=2 expandtab:
---

- name: assertions
  assert:
    that:
    - os_install_method in ["cdrom"]
    - os_kickstart_version is defined
    - os_wheel_users is defined
    - os_fqdn is defined
    - dest is defined

- name: debug
  debug: var=os_fqdn.split('.')[0]
  tags:
  - never
  - debug

- name: debug
  debug: var=os_network
  tags:
  - never
  - debug

- name: kickstart file is present
  with_first_found:
  - "{{ src|default(omit) }}"
  - ks.j2
  template:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: 0644

...
