# vim: set ft=yaml ts=2 expandtab:
---

os_install_type: install
os_install_method: cdrom

os_keyboard:
- at
- us
- us-mac
- at-mac

os_lang:
- en_US.UTF-8
- de_AT.UTF-8

os_timezone: Europe/Vienna
os_utc: true

os_network:
  devices:
    link:
      ipv4:
        ip: dhcp
      ipv6:
        ip: auto

# only for virtual machines
os_ram: 4096
os_disk_size: 20

...
