---
galaxy_info:
  author: Markus Falb <markus.falb@mafalb.at>
  description: Ansible role for installing VMs with virt-install
  license: GPLv3
  min_ansible_version: 2.9

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
  - libvirt
  - install

dependencies:
- mafalb.os.cfg
