---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v
  ansible-lint -v vars/*.yml
  flake8 -v

platforms:
  - name: fedora
    image: fedora:latest
provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"
verifier:
  name: ansible
  lint:
    name: ansible-lint
