# vim: ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all

  vars_files:
  - vars/main.yml

  tasks:

  - name: check kickstarts
    loop:
    - RHEL8
    - RHEL7
    - RHEL6
    changed_when: false
    command: ksvalidator -v {{ item }} /tmp/kickstart-{{ item }}.ks

  - name: check kickstarts
    loop:
    - RHEL8
    - RHEL7
    - RHEL6
    changed_when: false
    command: ksvalidator -v {{ item }} /tmp/kickstart-{{ item }}-local.ks
    
  - name: check kickstarts
    loop: "{{ ['RHEL8','RHEL7','RHEL6']|product(['ipv6_only_static','ipv6_only_static_wo_gateway','ipv4_only_static','ipv4_only_static_wo_gateway','auto','no_ipv4','no_ipv6'])|list }}" # noqa 204
    changed_when: false
    command: ksvalidator -v {{ item[0] }} /tmp/kickstart-{{ item[0] }}-{{ item[1] }}.ks

  - name: check kickstarts for missing whitespace
    loop: "{{ ['RHEL8','RHEL7','RHEL6']|product(['ipv6_only_static','ipv6_only_static_wo_gateway','ipv4_only_static','ipv4_only_static_wo_gateway','auto','no_ipv4','no_ipv6'])|list }}" # noqa 204
    changed_when: false
    failed_when: __whitespace.rc == 0
    command: grep -P -- '\w--' /tmp/kickstart-{{ item[0] }}-{{ item[1] }}.ks
    register: __whitespace

  - name: clock is in utc
    changed_when: false
    command: grep -- --utc /tmp/kickstart-RHEL8.ks

  - name: check /tmp/kickstart-RHEL8-local.ks
    changed_when: false
    command: ksvalidator -v RHEL8 /tmp/kickstart-RHEL8-local.ks

  - name: clock is not in utc
    changed_when: false
    failed_when: __not_utc.rc == 0
    command: grep -- --utc /tmp/kickstart-RHEL8-local.ks
    register: __not_utc

...
